name: xbb_start
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  dio: ^5.3.3
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.4
  fluttertoast: 8.2.2
  get: ^4.6.6
  http: ^1.1.0
  logger: ^2.0.2+1
  lottie: ^2.7.0
  open_file: ^3.3.2
  package_info: ^2.0.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/equipment_detail/
    - assets/hero_detail/
    - assets/calendar/
    - assets/lottie/
